version: '3.9'

services:
  server:
    build: .
    ports:
      - '8080:8080'
  db:
    image: 'postgres'
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'simpleChartingAppProject'
      POSTGRES_USER: 'chartingApp'